import { ExperienceSectionType } from '@/lib/types/sections';

export const experienceSection: ExperienceSectionType = {
  title: "where i've worked",
  experiences: [
    {
      company: 'Amazon',
      companyUrl: 'https://www.amazon.com/',
      role: 'Full Stack Engineer',
      started: 'Dec 2023',
      upto: 'Aug 2025',
      tasks: [
        'Developed and maintained an internal staff management platform, streamlining HR, scheduling, and operational workflows, improving efficiency and reducing administrative overhead.',
        'Built and deployed serverless functions with AWS Lambda to handle event-driven processes, reducing infrastructure costs and enabling scalable, on-demand execution.',
        'Designed secure, event-driven architectures by integrating AWS Cognito with Amazon API Gateway for authentication and role-based access control, and implemented scalable business logic with AWS Lambda.',
        'Implemented real-time communication features using WebSockets, enabling instant notifications, scheduling updates, and live dashboard refreshes.',
        'Managed secure, isolated environments with Amazon VPC, applying security groups and subnet configurations to safeguard sensitive data.',
        'Optimized document storage and delivery with Amazon S3 and CloudFront, while applying AWS KMS encryption to protect employee and business data.',
        'Leveraged Amazon DynamoDB for high-throughput, low-latency session data and analytics, complemented by Amazon RDS (PostgreSQL) for transactional business records.',
        'Integrated AWS SNS and SQS to power event-driven messaging workflows, including staff notifications, task scheduling, and approval processes.',
        'Orchestrated multi-step business processes with AWS Step Functions, automating onboarding sequences, compliance checks, and recurring operations.',
        'Monitored application performance and traced errors using Amazon CloudWatch and AWS X-Ray, improving system reliability and accelerating debugging.',
        'Automated builds, tests, and deployments with AWS CodePipeline and CodeBuild, accelerating release cycles and improving deployment reliability.',
        'Applied security best practices with AWS WAF and AWS Secrets Manager, protecting APIs against attacks and securely managing sensitive configurations.',
        'Streamlined provisioning and deployments through AWS CLI scripting and automation, reducing setup time for infrastructure changes.',
        'Established automated testing pipelines with unit and integration coverage, ensuring platform reliability and minimizing production defects.',
        'Collaborated with cross-functional teams to deliver new features and process improvements, boosting staff productivity and reducing operational delays.',
      ],
    },
    {
      company: 'Differenz System',
      companyUrl: 'https://www.differenzsystem.com/',
      role: 'Senior Full Stack Engineer',
      started: 'Aug 2018',
      upto: 'Nov 2023',
      tasks: [
        'Led the end-to-end development of a multi-tenant SaaS platform, architecting a secure, scalable, and maintainable solution for enterprise onboarding and customer growth.',
        'Designed and integrated REST and GraphQL APIs to unify multiple services into a single high-performance platform, ensuring consistent state synchronization and seamless interoperability.',
        'Built asynchronous background processing pipelines using AWS SQS as the broker, integrating transactional email delivery through Amazon SES and FastMail to improve system reliability.',
        'Leveraged PostgreSQL for relational data, DynamoDB for high-scale key-value storage, and Redis for caching and request throttling, optimizing scalability, availability, and response times.',
        'Automated backend testing pipelines with GitHub Actions, reducing execution time by 40% and accelerating release cycles for faster delivery of new features.',
        'Architected a serverless authentication and authorization system with AWS Lambda, API Gateway, and Cognito, adopting a microservice architecture to improve scalability, security, and reduce operational overhead.',
        'Enabled enterprise Single Sign-On (SSO) with Okta, Google, and GitHub, and integrated workflows with AWS Marketplace, Amazon Business, Azure, and GCP to expand product distribution channels.',
        'Integrated monitoring and error tracking with Sentry, enabling proactive debugging, improved reliability, and faster resolution of production issues.',
        'Mentored and guided a team of 4 developers through architecture planning, code reviews, and implementation best practices, raising overall code quality and delivery standards.',
        'Coordinated project workflows in Jira, managing sprint planning, progress tracking, and cross-functional collaboration to ensure timely delivery.',
      ],
    },
    {
      company: 'Empat',
      companyUrl: 'https://www.empat.tech/',
      role: 'Backend Developer',
      started: 'Oct 2015',
      upto: 'Apr 2018',
      tasks: [
        'Developed and maintained backend services supporting core business logic and data workflows for multiple enterprise and client-facing applications.',
        'Designed and documented secure RESTful APIs to enable seamless integration with partner services and internal platforms, improving interoperability and system reliability.',
        'Implemented asynchronous background processing with a distributed task queue and message broker, enabling efficient execution of long-running jobs and improving system scalability.',
        'Optimized database queries and enforced data integrity in relational environments, ensuring consistent performance under high transactional loads.',
        'Built automated testing pipelines with unit and integration coverage, reducing regressions and improving release confidence.',
        'Collaborated with cross-functional teams to refine API contracts, resolve production issues, and deliver features on schedule, enhancing product stability and customer satisfaction.',
      ],
    },
  ],
};
